#! /bin/bash

# To enable this hook, copy this file to ".git/hooks/pre-commit".

export PYTHONWARNINGS="ignore"

black materialscoord

status=0
files=$(git diff --diff-filter=d --cached --name-only | grep -E 'materialscoord.*\.(py)$' | sed '/test_/d')
files=`echo $files | tr '\n' ' '`
pycodestyle materialscoord $files
if [ $? -ne 0 ]; then
  echo "Bad code style detected by pycodestyle. Fix before commit."
  exit 1
fi
flake8 materialscoord $files
if [ $? -ne 0 ]; then
  echo "Bad code style detected by flake8. Fix before commit."
  exit 1
fi
pydocstyle --match='(?!test_).*\.py' materialscoord $files
if [ $? -ne 0 ]; then
  echo "Bad doc style detected. Fix before commit."
  exit 1
fi
