#! /bin/bash

# To enable this hook, copy this file to ".git/hooks/pre-commit".

export PYTHONWARNINGS="ignore"

black amset
black tests

isort --profile black amset
isort --profile black tests

status=0
files=$(git diff --diff-filter=d --cached --name-only | grep -E 'amset.*\.(py)$' | sed '/test/d')
files=`echo $files | tr '\n' ' '`
pycodestyle amset $files
if [ $? -ne 0 ]; then
  echo "Bad code style detected by pycodestyle. Fix before commit."
  exit 1
fi
flake8 amset $files --exclude '*test*'
if [ $? -ne 0 ]; then
  echo "Bad code style detected by flake8. Fix before commit."
  exit 1
fi
#pydocstyle --match='(?!test_).*\.py' amset $files
#if [ $? -ne 0 ]; then
#  echo "Bad doc style detected. Fix before commit."
#  exit 1
#fi
