from typing import Optional, List

from amset.interpolate.base import AbstractInterpolater
from amset.interpolate.boltztrap1 import BoltzTraP1Interpolater
from amset.interpolate.boltztrap2 import BoltzTraP2Interpolater
from amset.interpolate.parabolic import ParabolicInterpolater
from pymatgen.electronic_structure.bandstructure import BandStructure


def get_interpolater(band_structure: BandStructure, num_electrons: int,
                     coeff_file: Optional[str] = None,
                     parabolic_band_parameters: Optional[List] = None,
                     interpolation_type: str = "boltztrap2"
                     ) -> AbstractInterpolater:
    """Gets an band structure iterpolater based on the passed options.

    Args:
        band_structure: A pymatgen band structure object.
        num_electrons: The number of electrons in the system.
        coeff_file: Path to a band structure coefficients file generated by a
            modified version of BoltzTraP1. If ``None``, BoltzTraP1 will be run
            to generate the file. Note, this requires a patched version of
            BoltzTraP1. More information can be found in the
            "patch_for_boltztrap" directory.
        parabolic_band_parameters: The parabolic bands definition. This should
            be formatted as a list containing the parameters for each band.
            Each band can contain multiple band extrema. The general format for
            each extrema is::

                [k-point, offset, effective_mass]

            Where k-point is the fractional coordinate of the extrema,
            offset is the offset from the reference energy (zero for a valence
            band and the band gap energy for a conduction band), and effective
            mass is the valley effective mass. For example, the following
            definition::

                [[[[0.5, 0.5, 0.5], 0, 0.1]], [[0, 0, 0], 0.5, 0.2]]]]

            Indicates a single band system with two extrema. The first
            extrema is centered at [0.5 0.5 0.5], has an offset of
            0 (e.g. it is the CBM and VBM), and has an effective mass of 0.1.
            The second extrema is centered at Gamma and is 0.5 eV higher in
            energy, with an effective mass of 0.2.
        interpolation_type: The type of interpolater to return. The options
            are "boltztrap1", "boltztrap2" (default), "parabolic".

    Returns:

    """
    if interpolation_type == "boltztrap2":
        return BoltzTraP2Interpolater(band_structure, num_electrons)
    elif interpolation_type == "boltztrap1":
        return BoltzTraP1Interpolater(band_structure, num_electrons,
                                      coeff_file=coeff_file)
    elif interpolation_type == "parabolic":
        return ParabolicInterpolater(band_structure, num_electrons,
                                     parabolic_band_parameters)
